-- Public-source directory, researched 2026-09-25: 2 entries x 5 categories x 8 destinations.
-- Source checking establishes the published identity/location/service only. These
-- are external referrals, not onboarded partners, field visits, licence checks,
-- live availability or Mshwar bookings. Existing trust functions remain unchanged.
-- Explicit review dates never move forward merely because a migration is rerun.
CREATE TABLE app.destination_service_sources (
    id text PRIMARY KEY,
    destination_slug text NOT NULL,
    category text NOT NULL CHECK (category IN ('transport','drivers','money','eat','stay')),
    name text NOT NULL CHECK (btrim(name) <> ''),
    locality text NOT NULL CHECK (btrim(locality) <> ''),
    service_type text NOT NULL CHECK (service_type IN ('car_rental','driver_service','money_transfer','bank','atm','eat','stay')),
    coverage text NOT NULL CHECK (coverage IN ('local','airport','national')),
    source_url text NOT NULL CHECK (source_url ~ '^https://[^/[:space:]]+'),
    source_name text NOT NULL CHECK (btrim(source_name) <> ''),
    source_kind text NOT NULL CHECK (source_kind IN ('operator','directory')),
    checked_on date NOT NULL,
    review_by date NOT NULL CHECK (review_by >= checked_on),
    active boolean NOT NULL DEFAULT true
);
-- Text slugs allow the catalogue importer to create destinations after migrations.
-- Public reads still require an existing published destination.
CREATE INDEX destination_service_sources_destination_idx ON app.destination_service_sources(destination_slug, category);
ALTER TABLE app.destination_service_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE app.destination_service_sources FORCE ROW LEVEL SECURITY;
REVOKE ALL ON app.destination_service_sources FROM PUBLIC, mshwar_backend;

CREATE FUNCTION app.public_destination_service_sources(p_slug text)
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = app, public
AS $$
    SELECT coalesce(jsonb_agg(to_jsonb(s) - 'active' ORDER BY s.category, s.id), '[]'::jsonb)
    FROM app.destination_service_sources s
    WHERE s.destination_slug = p_slug AND s.active
      AND s.checked_on <= app.beirut_today() AND s.review_by >= app.beirut_today()
      AND EXISTS (SELECT 1 FROM app.destinations d WHERE d.slug = p_slug AND d.status = 'published')
$$;
REVOKE ALL ON FUNCTION app.public_destination_service_sources(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app.public_destination_service_sources(text) TO mshwar_backend;

INSERT INTO app.destination_service_sources
(id, destination_slug, category, name, locality, source_url, source_name, source_kind, service_type, coverage, checked_on, review_by)
SELECT id, destination_slug, category, name, locality, source_url, source_name, source_kind, service_type, coverage, checked_on, review_by
FROM jsonb_to_recordset($sources$
[
  {
    "id": "beirut-transport-1",
    "destination_slug": "beirut",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-transport-2",
    "destination_slug": "beirut",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-drivers-1",
    "destination_slug": "beirut",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-drivers-2",
    "destination_slug": "beirut",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-transport-1",
    "destination_slug": "mount-lebanon",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-transport-2",
    "destination_slug": "mount-lebanon",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-drivers-1",
    "destination_slug": "mount-lebanon",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-drivers-2",
    "destination_slug": "mount-lebanon",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-transport-1",
    "destination_slug": "north-lebanon",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-transport-2",
    "destination_slug": "north-lebanon",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-drivers-1",
    "destination_slug": "north-lebanon",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-drivers-2",
    "destination_slug": "north-lebanon",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-transport-1",
    "destination_slug": "akkar",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-transport-2",
    "destination_slug": "akkar",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-drivers-1",
    "destination_slug": "akkar",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-drivers-2",
    "destination_slug": "akkar",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-transport-1",
    "destination_slug": "beqaa",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-transport-2",
    "destination_slug": "beqaa",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-drivers-1",
    "destination_slug": "beqaa",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-drivers-2",
    "destination_slug": "beqaa",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-transport-1",
    "destination_slug": "baalbek-hermel",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-transport-2",
    "destination_slug": "baalbek-hermel",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-drivers-1",
    "destination_slug": "baalbek-hermel",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-drivers-2",
    "destination_slug": "baalbek-hermel",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-transport-1",
    "destination_slug": "south-lebanon",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-transport-2",
    "destination_slug": "south-lebanon",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-drivers-1",
    "destination_slug": "south-lebanon",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-drivers-2",
    "destination_slug": "south-lebanon",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-transport-1",
    "destination_slug": "nabatieh",
    "category": "transport",
    "name": "AVIS Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.avis.com.lb/Rafic-Hariri-International-Airport",
    "source_name": "AVIS Lebanon",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-transport-2",
    "destination_slug": "nabatieh",
    "category": "transport",
    "name": "Budget Lebanon",
    "locality": "Beirut Rafic Hariri International Airport",
    "source_url": "https://www.budget.com/en/locations/lb/beirut/bey",
    "source_name": "Budget",
    "source_kind": "operator",
    "service_type": "car_rental",
    "coverage": "airport",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-drivers-1",
    "destination_slug": "nabatieh",
    "category": "drivers",
    "name": "ALLO Taxi",
    "locality": "Lebanon",
    "source_url": "https://www.allotaxi.com/en/taxi-services",
    "source_name": "ALLO Taxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-drivers-2",
    "destination_slug": "nabatieh",
    "category": "drivers",
    "name": "TeleTaxi",
    "locality": "Lebanon",
    "source_url": "https://v2.teletaxi.com.lb/",
    "source_name": "TeleTaxi",
    "source_kind": "operator",
    "service_type": "driver_service",
    "coverage": "national",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-eat-1",
    "destination_slug": "beirut",
    "category": "eat",
    "name": "Liza Beirut",
    "locality": "Achrafieh, Beirut",
    "source_url": "https://lizabeirut.com/",
    "source_name": "Liza Beirut",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-eat-2",
    "destination_slug": "beirut",
    "category": "eat",
    "name": "Tawlet Mar Mikhael",
    "locality": "Mar Mikhael, Beirut",
    "source_url": "https://www.soukeltayeb.com/tawlet",
    "source_name": "Souk El Tayeb",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-stay-1",
    "destination_slug": "beirut",
    "category": "stay",
    "name": "Albergo Hotel",
    "locality": "Beirut",
    "source_url": "https://www.albergobeirut.com/",
    "source_name": "Albergo Hotel",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-stay-2",
    "destination_slug": "beirut",
    "category": "stay",
    "name": "Saifi Suites",
    "locality": "Maroun Naccache Avenue, Saifi, Beirut",
    "source_url": "https://saifisuites.com/",
    "source_name": "Saifi Suites",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-eat-1",
    "destination_slug": "mount-lebanon",
    "category": "eat",
    "name": "Mounir",
    "locality": "Broumana",
    "source_url": "https://mounirs.com/",
    "source_name": "Mounir Restaurant",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-eat-2",
    "destination_slug": "mount-lebanon",
    "category": "eat",
    "name": "Kasr Fakhreddine",
    "locality": "Al Rassif Street, Broumana",
    "source_url": "https://www.kaserfakhreddine.com/contact_us",
    "source_name": "Kasr Fakhreddine",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-stay-1",
    "destination_slug": "mount-lebanon",
    "category": "stay",
    "name": "Mir Amin Palace",
    "locality": "Beiteddine, Shouf",
    "source_url": "https://miraminpalace.com/",
    "source_name": "Mir Amin Palace",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-stay-2",
    "destination_slug": "mount-lebanon",
    "category": "stay",
    "name": "Burj On Bay",
    "locality": "Kfar Yassine, Keserwan",
    "source_url": "https://burjonbay.com/",
    "source_name": "Burj On Bay",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-eat-1",
    "destination_slug": "north-lebanon",
    "category": "eat",
    "name": "Lakkis Farm — Batroun",
    "locality": "Batroun",
    "source_url": "https://lakkisfarm.com/",
    "source_name": "Lakkis Farm",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-eat-2",
    "destination_slug": "north-lebanon",
    "category": "eat",
    "name": "San Stephano restaurants",
    "locality": "Sea Road, Batroun",
    "source_url": "https://www.sanstephano.com/",
    "source_name": "San Stephano Resort",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-stay-1",
    "destination_slug": "north-lebanon",
    "category": "stay",
    "name": "San Stephano Resort",
    "locality": "Sea Road, Batroun",
    "source_url": "https://www.sanstephano.com/",
    "source_name": "San Stephano Resort",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-stay-2",
    "destination_slug": "north-lebanon",
    "category": "stay",
    "name": "Miramar Hotel Resort & Spa",
    "locality": "Tripoli coast",
    "source_url": "https://miramar-lb.com/",
    "source_name": "Miramar",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-eat-1",
    "destination_slug": "akkar",
    "category": "eat",
    "name": "Karam’s Grand Restaurant",
    "locality": "Centre Karam, Qoubaiyat",
    "source_url": "https://www.beirut.com/en/directory/karams-grand-restaurant/",
    "source_name": "Beirut.com",
    "source_kind": "directory",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-eat-2",
    "destination_slug": "akkar",
    "category": "eat",
    "name": "Diwan Al Wadi",
    "locality": "Qoubaiyat, near Mar Chlita Church",
    "source_url": "https://www.beirut.com/en/64271/7-restaurants-you-need-to-try-in-qobayat/",
    "source_name": "Beirut.com",
    "source_kind": "directory",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-stay-1",
    "destination_slug": "akkar",
    "category": "stay",
    "name": "Graneroverde Resort",
    "locality": "Qoubaiyat",
    "source_url": "https://www.booking.com/hotel/lb/granoverde-resort.fr.html",
    "source_name": "Booking.com",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-stay-2",
    "destination_slug": "akkar",
    "category": "stay",
    "name": "Les Demeures",
    "locality": "Couvent Saint Doumit, Qoubaiyat",
    "source_url": "https://www.carmelliban.org/carmel-kobayat.php",
    "source_name": "Carmel Liban",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-eat-1",
    "destination_slug": "beqaa",
    "category": "eat",
    "name": "Tawlet Ammiq",
    "locality": "Ammiq, West Beqaa",
    "source_url": "https://www.soukeltayeb.com/tawlet",
    "source_name": "Souk El Tayeb",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-eat-2",
    "destination_slug": "beqaa",
    "category": "eat",
    "name": "Al Shams",
    "locality": "Zetlian, Anjar",
    "source_url": "https://restaurantalshams.com/",
    "source_name": "Al Shams",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-stay-1",
    "destination_slug": "beqaa",
    "category": "stay",
    "name": "Massabki Hotel",
    "locality": "Chtaura",
    "source_url": "https://www.baalbeck.org.lb/hotel/massabki-hotel/",
    "source_name": "Baalbeck International Festival",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-stay-2",
    "destination_slug": "beqaa",
    "category": "stay",
    "name": "Grand Kadri Hotel",
    "locality": "Zahle",
    "source_url": "https://www.grandkadrihotel.com/",
    "source_name": "Grand Kadri Hotel",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-eat-1",
    "destination_slug": "baalbek-hermel",
    "category": "eat",
    "name": "Lakkis Farm — Baalbek",
    "locality": "Baalbek",
    "source_url": "https://lakkisfarm.com/",
    "source_name": "Lakkis Farm",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-eat-2",
    "destination_slug": "baalbek-hermel",
    "category": "eat",
    "name": "Jawhari Sweets",
    "locality": "Baalbek",
    "source_url": "https://www.tripadvisor.com/Restaurant_Review-g295421-d3750718-Reviews-Jawhari_Sweets-Baalbeck_Bekaa_Governorate.html",
    "source_name": "Tripadvisor",
    "source_kind": "directory",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-stay-1",
    "destination_slug": "baalbek-hermel",
    "category": "stay",
    "name": "Kanaan Group Hotel",
    "locality": "Ras El Ain, Baalbek",
    "source_url": "https://www.booking.com/hotel/lb/kanaan-group.en-gb.html",
    "source_name": "Booking.com",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-stay-2",
    "destination_slug": "baalbek-hermel",
    "category": "stay",
    "name": "L’Annexe",
    "locality": "Baalbek",
    "source_url": "https://www.hotelibanais.com/travel/guesthouses/annexe-baalbek/",
    "source_name": "L’Hôte Libanais",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-eat-1",
    "destination_slug": "south-lebanon",
    "category": "eat",
    "name": "Dar Alma restaurant",
    "locality": "Old town waterfront, Tyre",
    "source_url": "https://daralmatyre.com/eatdrink.php",
    "source_name": "Dar Alma",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-eat-2",
    "destination_slug": "south-lebanon",
    "category": "eat",
    "name": "Rest House Tyr restaurant",
    "locality": "Tyre beach",
    "source_url": "https://resthouse-tyr.com.lb/",
    "source_name": "Rest House Tyr",
    "source_kind": "operator",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-stay-1",
    "destination_slug": "south-lebanon",
    "category": "stay",
    "name": "Dar Alma",
    "locality": "Old town waterfront, Tyre",
    "source_url": "https://daralmatyre.com/about.php",
    "source_name": "Dar Alma",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-stay-2",
    "destination_slug": "south-lebanon",
    "category": "stay",
    "name": "Rest House Tyr",
    "locality": "Tyre beach",
    "source_url": "https://resthouse-tyr.com.lb/",
    "source_name": "Rest House Tyr",
    "source_kind": "operator",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-eat-1",
    "destination_slug": "nabatieh",
    "category": "eat",
    "name": "Reef Zefta restaurant",
    "locality": "Mafrak Zefta, Pine Valley",
    "source_url": "https://www.booking.com/hotel/lb/reef-zafta.en-gb.html",
    "source_name": "Booking.com",
    "source_kind": "directory",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-eat-2",
    "destination_slug": "nabatieh",
    "category": "eat",
    "name": "Al Bohsasa Restaurant",
    "locality": "Hasbaya",
    "source_url": "https://wenrayhin.com/en/places/al-bohsasa-restaurant-hasbaya",
    "source_name": "WenRayhin",
    "source_kind": "directory",
    "service_type": "eat",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-stay-1",
    "destination_slug": "nabatieh",
    "category": "stay",
    "name": "Reef Zefta Hotel",
    "locality": "Mafrak Zefta, Pine Valley",
    "source_url": "https://www.booking.com/hotel/lb/reef-zafta.en-gb.html",
    "source_name": "Booking.com",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-stay-2",
    "destination_slug": "nabatieh",
    "category": "stay",
    "name": "Maison du Sud",
    "locality": "Ebel El Saqi, Marjeyoun",
    "source_url": "https://www.tripadvisor.com/Hotel_Review-g28132990-d28128872-Reviews-Maison_Du_Sud_Hotel_Furnished_Suites-Ebel_El_Saqi_Nabatiyeh_Governorate.html",
    "source_name": "Tripadvisor",
    "source_kind": "directory",
    "service_type": "stay",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-money-1",
    "destination_slug": "beirut",
    "category": "money",
    "name": "OMT — Achrafieh",
    "locality": "ABC Achrafieh, Alfred Naccache Street",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beirut-money-2",
    "destination_slug": "beirut",
    "category": "money",
    "name": "BoB Finance — Sidani",
    "locality": "Sidani Street, Hamra, near AUH",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-money-1",
    "destination_slug": "mount-lebanon",
    "category": "money",
    "name": "OMT — Jeita",
    "locality": "Jeita Main Road, toward Ajaltoun",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "mount-lebanon-money-2",
    "destination_slug": "mount-lebanon",
    "category": "money",
    "name": "BoB Finance — Jbeil",
    "locality": "Jbeil souk, Kordahi Center",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-money-1",
    "destination_slug": "north-lebanon",
    "category": "money",
    "name": "OMT — Tripoli",
    "locality": "Dam Wel Farz, Street 32, Dania Plaza",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "north-lebanon-money-2",
    "destination_slug": "north-lebanon",
    "category": "money",
    "name": "BoB Finance — Tripoli Tall",
    "locality": "Tall Street, next to Al Alam pharmacy",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-money-1",
    "destination_slug": "akkar",
    "category": "money",
    "name": "OMT — El Mhammara",
    "locality": "Aabdeh Highway, Al Rashid building, Mhammara",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "akkar-money-2",
    "destination_slug": "akkar",
    "category": "money",
    "name": "Byblos Bank — Halba",
    "locality": "Main Road Al Abdeh, Naim Center, Halba",
    "source_url": "https://www.byblosbank.com/BranchLocator.aspx",
    "source_name": "Byblos Bank",
    "source_kind": "operator",
    "service_type": "bank",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-money-1",
    "destination_slug": "beqaa",
    "category": "money",
    "name": "OMT — Zahle",
    "locality": "Zahle Boulevard, Zalaquett Center",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "beqaa-money-2",
    "destination_slug": "beqaa",
    "category": "money",
    "name": "BoB Finance — Zahle",
    "locality": "Main Street, near DOYEN, Zahle",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-money-1",
    "destination_slug": "baalbek-hermel",
    "category": "money",
    "name": "Byblos Bank ATM — Dar El Amal Hospital",
    "locality": "Dar El Amal Hospital, Baalbek",
    "source_url": "https://www.byblosbank.com/BranchLocator.aspx",
    "source_name": "Byblos Bank",
    "source_kind": "operator",
    "service_type": "atm",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "baalbek-hermel-money-2",
    "destination_slug": "baalbek-hermel",
    "category": "money",
    "name": "BSL Bank — Baalbeck",
    "locality": "Baalbek",
    "source_url": "https://www.bslbank.com/branches-information",
    "source_name": "BSL Bank",
    "source_kind": "operator",
    "service_type": "bank",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-money-1",
    "destination_slug": "south-lebanon",
    "category": "money",
    "name": "OMT — Saida",
    "locality": "President Adel Osseiran Street, Eastern Boulevard",
    "source_url": "https://www.omt.com.lb/en/contact/network",
    "source_name": "OMT",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "south-lebanon-money-2",
    "destination_slug": "south-lebanon",
    "category": "money",
    "name": "BoB Finance — Tyre Al Ramel",
    "locality": "Hiram Street, facing Al Nabeel Pastry, Tyre",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-money-1",
    "destination_slug": "nabatieh",
    "category": "money",
    "name": "BoB Finance — Nabatieh",
    "locality": "Main Street, Deir Al Zahrani, facing Al Abdalah bakery",
    "source_url": "https://bob-finance.com/Flagship.aspx",
    "source_name": "BoB Finance",
    "source_kind": "operator",
    "service_type": "money_transfer",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  },
  {
    "id": "nabatieh-money-2",
    "destination_slug": "nabatieh",
    "category": "money",
    "name": "Byblos Bank — Nabatieh",
    "locality": "Al Jazaer Quarter, Youssef Bek Zein Avenue, Sabbagh building",
    "source_url": "https://www.byblosbank.com/BranchLocator.aspx",
    "source_name": "Byblos Bank",
    "source_kind": "operator",
    "service_type": "bank",
    "coverage": "local",
    "checked_on": "2026-09-25",
    "review_by": "2026-12-24"
  }
]
$sources$::jsonb) AS s(
    id text, destination_slug text, category text, name text, locality text,
    source_url text, source_name text, source_kind text, service_type text,
    coverage text, checked_on date, review_by date
);
