import type { Locale } from "@/lib/locale";
export type PolicyKind = "privacy" | "terms" | "cancellation" | "community";
type Policy = { title: string; sections: { title: string; body: string }[] };
export const policies: Record<Locale, Record<PolicyKind, Policy>> = {
  en: {
    privacy: { title: "Privacy policy", sections: [
      { title: "What we collect", body: "Mshwar uses account and contact details, trip preferences you provide, bookings, reviews and business verification documents to operate the service. Location is used when you choose a place, pin or device location. Do not include identity documents or payment details in planning prompts." },
      { title: "Purpose and choice", body: "Account security, booking fulfilment, fraud prevention and essential notifications are necessary to provide the service. Saved personalisation and marketing are separate, optional choices, off by default. You can grant or withdraw either in Settings without losing booking access. A current trip can still use the preferences you explicitly enter for that trip." },
      { title: "Sharing and service providers", body: "Businesses receive the information needed to fulfil your booking. Public reviews and shared trip information are visible to their intended audience; share links can be revoked by the trip owner. Hosting, maps, image storage, communications and payment providers may process information for these purposes. We do not sell your personal information. Verification files are private and accessible through expiring links." },
      { title: "Retention and your controls", body: "Settings lets you export your information, reset personalisation or delete your account. Deletion anonymises your profile and revokes sessions. Booking, accounting, consent and security records may be retained for dispute resolution, fraud prevention and applicable obligations. Existing recipients may retain information already delivered to them. Contact support through Contact for access, correction or retention questions." },
      { title: "Cookies and diagnostics", body: "Session, language, guest access and consent-choice storage are essential. Optional analytics stays off unless you enable it in Cookie choices; you can withdraw that choice at any time. Operational diagnostics exclude passwords, tokens and payment references. No optional analytics provider is enabled in this pilot." },
    ] },
    terms: { title: "Terms of service", sections: [
      { title: "Using Mshwar", body: "Mshwar helps travellers discover, plan and request or book experiences offered by businesses. Provide accurate information, keep your account secure and use the service lawfully. Only accept terms or make bookings if you can enter the relevant agreement; obtain a parent or guardian’s involvement where required." },
      { title: "Plans and bookings", body: "AI-generated plans are suggestions. Confirm current availability, accessibility, weather and safety conditions with the business. The checkout shows the price, currency, fulfilment details and cancellation policy that apply to the booking. A request or payment attempt is not confirmation; rely on the recorded booking status." },
      { title: "Payments and pilot", body: "Test-mode payments do not move real funds. Mshwar will identify the payment provider and payment mode at checkout. Production payments require an approved acquiring provider; availability must not be inferred from a test transaction." },
      { title: "Responsibilities and disputes", body: "Businesses are responsible for accurate listings and delivering the agreed experience. Travellers must follow venue rules and disclose relevant requirements directly to the provider. Contact the business or Mshwar support promptly about a problem. These terms do not remove rights that applicable law does not allow to be waived." },
      { title: "Access and changes", body: "Mshwar may restrict access to prevent abuse or investigate a policy violation. Where appropriate, support can review a restriction. Material policy changes will be dated and communicated before they apply; optional consent remains revocable. Contact support through Contact for questions." },
    ] },
    cancellation: { title: "Cancellation policy", sections: [
      { title: "Your booking’s policy", body: "The cancellation rules displayed and recorded at checkout govern your booking. Check the applicable deadline, timezone and refund amount before confirming. Different experiences may have different rules; no universal free-cancellation period is promised." },
      { title: "Cancelling", body: "Open your booking and review the cancellation preview. Submit the cancellation only when you accept the displayed consequences. A cancelled booking and a completed refund are distinct states. Keep the booking reference and contact support if the outcome differs from the recorded policy." },
      { title: "Refunds and interruptions", body: "Refund eligibility is calculated from the policy saved with the booking. Timing depends on the payment provider; test-mode refunds are simulated. If a business cancels or weather affects fulfilment, contact support for the options applicable to that booking. Mshwar does not silently move or replace confirmed bookings." },
    ] },
    community: { title: "Community guidelines", sections: [
      { title: "Respect people and places", body: "Treat travellers, hosts and local communities with respect. Harassment, discrimination, threats, fraud and illegal activity are prohibited. Follow venue rules and protect natural and cultural sites." },
      { title: "Honest contributions", body: "Publish reviews based on your own experience. Do not post private information, impersonate others, manipulate votes or submit promotional spam. Businesses may respond to reviews but cannot edit or remove a traveller’s review." },
      { title: "Sharing and moderation", body: "Share trip links only with the intended people and choose the appropriate viewing, voting or editing permissions. Report harmful reviews through the report control. Moderators may restrict content or accounts with a recorded reason; contact support to request review of a decision. Use local emergency services for immediate danger." },
    ] },
  },
  fr: {
    privacy: { title: "Politique de confidentialité", sections: [
      { title: "Données collectées", body: "Mshwar utilise les données du compte, les coordonnées, les préférences fournies, les réservations, les avis et les justificatifs professionnels pour assurer le service. La localisation est utilisée lorsque vous choisissez un lieu, une épingle ou la position de votre appareil. N’incluez aucun document d’identité ni donnée de paiement dans vos demandes de planification." },
      { title: "Finalités et choix", body: "La sécurité, la réalisation des réservations, la prévention de la fraude et les notifications essentielles sont nécessaires au service. La personnalisation enregistrée et le marketing sont deux choix facultatifs, désactivés par défaut. Vous pouvez les accepter ou les retirer séparément dans les paramètres sans perdre l’accès aux réservations. Les préférences saisies explicitement pour un voyage restent utilisables pour ce voyage." },
      { title: "Partage et prestataires", body: "Les entreprises reçoivent les informations nécessaires à votre réservation. Les avis publics et les voyages partagés sont visibles par leur public prévu ; le propriétaire peut révoquer les liens. Les prestataires d’hébergement, de cartes, d’images, de communication et de paiement peuvent traiter les données pour ces finalités. Nous ne vendons pas vos données. Les justificatifs restent privés et leurs liens expirent." },
      { title: "Conservation et droits", body: "Les paramètres permettent d’exporter vos données, de réinitialiser la personnalisation ou de supprimer votre compte. La suppression anonymise le profil et révoque les sessions. Les données de réservation, de comptabilité, de consentement et de sécurité peuvent être conservées pour les litiges, la prévention de la fraude et les obligations applicables. Les destinataires peuvent conserver les informations déjà reçues. Utilisez Contact pour toute demande d’accès, de correction ou de conservation." },
      { title: "Cookies et diagnostics", body: "Le stockage de session, de langue, d’accès invité et de choix de consentement est essentiel. L’analyse facultative reste désactivée sauf accord dans Choix des cookies, révocable à tout moment. Les diagnostics excluent les mots de passe, jetons et références de paiement. Aucun prestataire d’analyse facultative n’est activé dans ce pilote." },
    ] },
    terms: { title: "Conditions d’utilisation", sections: [
      { title: "Utilisation", body: "Mshwar permet de découvrir, planifier et demander ou réserver des expériences proposées par des entreprises. Fournissez des informations exactes, protégez votre compte et respectez la loi. Vous devez pouvoir conclure l’accord concerné ; faites intervenir un parent ou un tuteur si nécessaire." },
      { title: "Plans et réservations", body: "Les plans générés par l’IA sont des suggestions. Vérifiez disponibilité, accessibilité, météo et sécurité auprès de l’entreprise. Le paiement présente le prix, la devise, les modalités et la politique d’annulation applicables. Une demande ou une tentative de paiement n’est pas une confirmation : consultez le statut enregistré." },
      { title: "Paiements et pilote", body: "Les paiements de test ne transfèrent aucun fonds réel. Le prestataire et le mode de paiement seront indiqués au paiement. Les paiements réels nécessitent un acquéreur approuvé ; un test ne prouve pas leur disponibilité." },
      { title: "Responsabilités et litiges", body: "Les entreprises sont responsables de l’exactitude des annonces et de la prestation convenue. Les voyageurs doivent respecter les règles du lieu et communiquer leurs besoins au prestataire. Signalez rapidement les problèmes à l’entreprise ou au support Mshwar. Les droits impératifs prévus par la loi restent applicables." },
      { title: "Accès et modifications", body: "Mshwar peut limiter l’accès pour prévenir un abus ou examiner une violation. Le support peut réexaminer une restriction lorsque cela convient. Les changements importants seront datés et communiqués avant leur application. Le consentement facultatif reste révocable. Utilisez Contact pour vos questions." },
    ] },
    cancellation: { title: "Politique d’annulation", sections: [
      { title: "Politique de votre réservation", body: "Les règles affichées et enregistrées au paiement régissent votre réservation. Vérifiez le délai, le fuseau horaire et le montant remboursable avant de confirmer. Les expériences peuvent avoir des règles différentes ; aucune période universelle d’annulation gratuite n’est promise." },
      { title: "Annuler", body: "Ouvrez la réservation et consultez l’aperçu de l’annulation. Confirmez uniquement si vous acceptez les conséquences affichées. Une réservation annulée et un remboursement terminé sont des états distincts. Conservez la référence et contactez le support si le résultat diffère de la politique enregistrée." },
      { title: "Remboursements et interruptions", body: "Le remboursement est calculé selon la politique enregistrée avec la réservation. Le délai dépend du prestataire ; les remboursements de test sont simulés. En cas d’annulation par l’entreprise ou d’intempéries, contactez le support pour les options applicables. Mshwar ne déplace ni ne remplace silencieusement les réservations confirmées." },
    ] },
    community: { title: "Règles communautaires", sections: [
      { title: "Respect", body: "Respectez voyageurs, hôtes et communautés locales. Harcèlement, discrimination, menaces, fraude et activités illégales sont interdits. Respectez les lieux et protégez le patrimoine naturel et culturel." },
      { title: "Contributions honnêtes", body: "Publiez des avis fondés sur votre expérience. Ne divulguez pas d’informations privées, n’usurpez pas d’identité et ne manipulez pas les votes. Le spam est interdit. Les entreprises peuvent répondre aux avis, mais ne peuvent ni modifier ni supprimer ceux des voyageurs." },
      { title: "Partage et modération", body: "Partagez les liens uniquement avec les personnes prévues et choisissez les droits de lecture, de vote ou de modification adaptés. Signalez les avis nuisibles avec le bouton de signalement. Les modérateurs peuvent restreindre contenus ou comptes avec un motif enregistré ; demandez un réexamen au support. Contactez les services d’urgence locaux en cas de danger immédiat." },
    ] },
  },
  ar: {
    privacy: { title: "سياسة الخصوصية", sections: [
      { title: "البيانات التي نجمعها", body: "يستخدم مشوار بيانات الحساب والتواصل والتفضيلات التي تقدمها والحجوزات والتقييمات ومستندات التحقق من الأعمال لتشغيل الخدمة. نستخدم الموقع عندما تختار مكاناً أو دبوساً أو موقع جهازك. لا تُدخل مستندات الهوية أو بيانات الدفع في طلبات التخطيط." },
      { title: "الأغراض والاختيار", body: "أمان الحساب وتنفيذ الحجز ومنع الاحتيال والإشعارات الأساسية ضرورية للخدمة. تخصيص التجربة المحفوظ والتسويق خياران منفصلان واختياريان، ومعطّلان افتراضياً. يمكنك الموافقة على كل منهما أو سحبها من الإعدادات دون فقدان الوصول إلى الحجوزات. تبقى التفضيلات التي تدخلها صراحة لرحلة معينة قابلة للاستخدام لتلك الرحلة." },
      { title: "المشاركة ومزودو الخدمة", body: "تتلقى الأعمال المعلومات اللازمة لتنفيذ حجزك. تظهر التقييمات العامة ومعلومات الرحلات المشتركة للجمهور المقصود، ويمكن لصاحب الرحلة إلغاء روابط المشاركة. قد يعالج مزودو الاستضافة والخرائط والصور والتواصل والدفع البيانات لهذه الأغراض. لا نبيع بياناتك الشخصية. مستندات التحقق خاصة وروابط الوصول إليها مؤقتة." },
      { title: "الاحتفاظ والتحكم", body: "تتيح الإعدادات تصدير بياناتك أو إعادة ضبط التخصيص أو حذف الحساب. يؤدي الحذف إلى إخفاء بيانات الملف وإلغاء الجلسات. قد نحتفظ بسجلات الحجز والمحاسبة والموافقة والأمان لحل النزاعات ومنع الاحتيال والالتزامات المعمول بها. قد يحتفظ المستلمون بمعلومات سبق إرسالها إليهم. استخدم صفحة التواصل لطلبات الوصول أو التصحيح أو أسئلة الاحتفاظ." },
      { title: "ملفات الارتباط والتشخيص", body: "تخزين الجلسة واللغة ووصول الضيف وخيار الموافقة أساسي. تبقى التحليلات الاختيارية معطلة ما لم توافق عليها في خيارات ملفات الارتباط، ويمكنك سحب الموافقة في أي وقت. لا تتضمن سجلات التشخيص كلمات المرور أو الرموز أو مراجع الدفع. لا يوجد مزود تحليلات اختياري مفعّل في هذه التجربة." },
    ] },
    terms: { title: "شروط الاستخدام", sections: [
      { title: "استخدام مشوار", body: "يساعد مشوار المسافرين على اكتشاف وتخطيط وطلب أو حجز تجارب تقدمها الأعمال. قدّم معلومات صحيحة واحمِ حسابك واستخدم الخدمة بشكل قانوني. لا توافق على الشروط أو تحجز إلا إذا كنت مؤهلاً لإبرام الاتفاق المعني، مع إشراك ولي الأمر عند الحاجة." },
      { title: "الخطط والحجوزات", body: "الخطط التي ينتجها الذكاء الاصطناعي اقتراحات. تحقّق من التوفر وإمكانية الوصول والطقس والسلامة مع مقدم التجربة. تعرض صفحة الدفع السعر والعملة وتفاصيل التنفيذ وسياسة الإلغاء الخاصة بالحجز. الطلب أو محاولة الدفع ليسا تأكيداً؛ اعتمد على حالة الحجز المسجلة." },
      { title: "الدفع والتجربة الأولية", body: "لا تنقل مدفوعات الاختبار أموالاً حقيقية. يُعرض مزود الدفع ووضع الدفع عند إتمام الحجز. تتطلب المدفوعات الفعلية جهة تحصيل معتمدة؛ نجاح اختبار لا يعني توفر الدفع الفعلي." },
      { title: "المسؤوليات والنزاعات", body: "تتحمل الأعمال مسؤولية دقة العروض وتنفيذ التجربة المتفق عليها. على المسافرين اتباع قواعد المكان وإبلاغ المزود بالاحتياجات ذات الصلة. أبلغ العمل أو دعم مشوار سريعاً عن أي مشكلة. لا تلغي هذه الشروط الحقوق التي لا يسمح القانون بالتنازل عنها." },
      { title: "الوصول والتغييرات", body: "قد يقيّد مشوار الوصول لمنع إساءة الاستخدام أو التحقيق في مخالفة. يمكن للدعم مراجعة التقييد عند الاقتضاء. تُؤرّخ التغييرات المهمة وتُبلّغ قبل تطبيقها، وتبقى الموافقة الاختيارية قابلة للسحب. استخدم صفحة التواصل للاستفسارات." },
    ] },
    cancellation: { title: "سياسة الإلغاء", sections: [
      { title: "سياسة حجزك", body: "تحكم حجزك قواعد الإلغاء المعروضة والمسجلة عند الدفع. راجع المهلة والمنطقة الزمنية والمبلغ القابل للاسترداد قبل التأكيد. قد تختلف القواعد بين التجارب؛ لا نعد بفترة إلغاء مجاني موحدة." },
      { title: "كيفية الإلغاء", body: "افتح الحجز وراجع معاينة الإلغاء. أكّد الإلغاء فقط إذا قبلت النتائج المعروضة. إلغاء الحجز واكتمال رد المبلغ حالتان مختلفتان. احتفظ بمرجع الحجز وتواصل مع الدعم إذا اختلفت النتيجة عن السياسة المسجلة." },
      { title: "الاسترداد والتعطّل", body: "يُحسب الاسترداد وفق السياسة المحفوظة مع الحجز. تعتمد المدة على مزود الدفع، والاستردادات في وضع الاختبار محاكاة. إذا ألغى العمل أو أثّر الطقس على التنفيذ، تواصل مع الدعم لمعرفة الخيارات الخاصة بحجزك. لا ينقل مشوار الحجوزات المؤكدة أو يستبدلها بصمت." },
    ] },
    community: { title: "إرشادات المجتمع", sections: [
      { title: "احترام الناس والأماكن", body: "احترم المسافرين والمضيفين والمجتمعات المحلية. يُحظر التحرش والتمييز والتهديد والاحتيال والنشاط غير القانوني. اتبع قواعد المكان واحمِ المواقع الطبيعية والثقافية." },
      { title: "مساهمات صادقة", body: "اكتب تقييمات مبنية على تجربتك. لا تنشر معلومات خاصة ولا تنتحل هوية ولا تتلاعب بالأصوات ولا ترسل إعلانات مزعجة. يمكن للأعمال الرد على التقييمات، لكن لا يمكنها تعديل تقييم المسافر أو حذفه." },
      { title: "المشاركة والإشراف", body: "شارك روابط الرحلة مع الأشخاص المقصودين فقط واختر صلاحيات المشاهدة أو التصويت أو التعديل المناسبة. أبلغ عن التقييمات الضارة عبر أداة الإبلاغ. يمكن للمشرفين تقييد المحتوى أو الحسابات بسبب مسجل؛ تواصل مع الدعم لطلب مراجعة القرار. اتصل بالطوارئ المحلية عند وجود خطر فوري." },
    ] },
  },
};
